### ISSUE TITLE
Random isn't reliable

### ISSUE THREAD

**Issue by VoilierBleu** [philhansen/WallpaperChanger#3] opened 2020-03-01 18:12 UTC
Hi,

i'm trying to use your utilitie to select randomly a wallpaper from a folder, but each time it's the same wallpaper.

any idea ?

Cheers.

**Comment by philhansen** [comment] 2020-03-01 23:02
I just tried the utility on my own system running Windows 10 and it worked fine.  What operating system are you using and are you using the latest version of the utility?  Keep in mind that the utility doesn't have any "memory" of the last wallpaper chosen at random, so it is entirely possible for the same wallpaper to be chosen multiple times in a row.  The more image files you have in the directory the less chance you will have for a repeat.  For example in my test directory I only have 4 wallpapers and running it 12 times in a row I did get the same wallpaper 3 times in a row.

A possible enhancement would be to keep a list in a local file of the last X wallpapers chosen so that it does not choose the same one in a row.

**Comment by VoilierBleu** [comment] 2020-03-02 20:24
Hi Phil,

thanks a lot for your fast reply. Using Windows 10 in the latest version.

In fact, i often reboot and come back after and it's often the same wallpaper, dunno why but it's remember me the random function in batch console, which is not very random.

I dochange wallpaper because i primary use a utility to grab wallpapers from bing repository, then if the wallpaper isn't good, i come back to my old favorites.

your proposal is really great ! I will try to count them next time with an excel sheet and will keep you informed

Regards,
Voilier.

**Comment by philhansen** [comment] 2020-12-04 01:17
I'm closing this for now.  The random selection is working as intended, which does unfortunately mean that multiple runs of the program could end up selecting the same random image.  How often this happens will probably be related to how many images are in the directory.

**Closed as completed by philhansen** 2020-12-04 01:17 UTC
